### ISSUE TITLE
Force load module failed: Unable to open file "SHLWAPI.dll"

### ISSUE THREAD

**Issue by KurenaiRyu** [bhhbazinga/Dyna-IL2CppDumper#1]
I used CE to inject the dll file to Uma musume(DMM ver) I got after compiling, but got an error :
<img width="272" alt="Snipaste_2021-03-21_06-36-07" src="https://user-images.githubusercontent.com/18627047/111887570-c6b53f00-89cd-11eb-948d-ac572b946208.png">

<img width="459" alt="Snipaste_2021-03-21_06-38-11" src="https://user-images.githubusercontent.com/18627047/111887697-afc31c80-89ce-11eb-81b7-a60aa4ae2f1b.png">

**Comment by bhhbazinga** [comment]
It seems CE can not open the game process，may be the process runnning with some mechanism of memory protection, you can try another injector , eg.SetWindowsHookEx inject. I have tried lsp inject, and it did work.

**Comment by bhhbazinga** [comment]
> I used CE to inject the dll file to Uma musume(DMM ver) I got after compiling, but got an error :
> <img alt="Snipaste_2021-03-21_06-36-07" width="272" src="https://user-images.githubusercontent.com/18627047/111887570-c6b53f00-89cd-11eb-948d-ac572b946208.png">
> 
> <img alt="Snipaste_2021-03-21_06-38-11" width="459" src="https://user-images.githubusercontent.com/18627047/111887697-afc31c80-89ce-11eb-81b7-a60aa4ae2f1b.png">

It seems CE can not open the game process，may be the process runnning with some mechanism of memory protection, you can try another injector , eg.SetWindowsHookEx inject. I have tried lsp inject, and it did work.

**Comment by KurenaiRyu** [comment]
> 
> It seems CE can not open the game process，may be the process runnning with some mechanism of memory protection, you can try another injector , eg.SetWindowsHookEx inject. I have tried lsp inject, and it did work.

抱歉我英文不是特别好，所以还是用中文交流吧XD  
就说我试了一下用[Xenos](https://github.com/DarthTon/Xenos)和[SetWindowsHookEx-Injector](https://github.com/DrNseven/SetWindowsHookEx-Injector)都不行
Xenos：
<img width="290" alt="Snipaste_2021-03-21_23-09-37" src="https://user-images.githubusercontent.com/18627047/111910022-87333500-8a57-11eb-94e2-63ed09baaaf5.png">
SetWindowsHookEx-Injector 则是没有任何响应，虽然执行注入的程序说是注入成功了，但是dll里面并没有执行(我也尝试过注入到别的程序当中去，应该是有一个命令行窗口出现的，并且日志文件也有，但是注入到游戏程序并没有窗口和日志文件） 
 
而lsp注入这个我搜了一下没有明白怎么操作，如果可以话能否给一些建议或者博文让我学习一下

**Comment by bhhbazinga** [comment]
> SetWindowsHookEx-Injecto
SetWindowsHookEx这个我没试过，你可以用进程查看器之类的工具确认下是否真的没注入进去。
LSP的话这个可能可以参考一下，不需要去hook任何socekt操作，只需要实现WSPStartUp，了解一下LSP是如何安装的协议如何重排，windows是如何枚举winsock目录里的协议链的。https://blog.csdn.net/Aaron133/article/details/78028942

**Comment by KurenaiRyu** [comment]
非常感谢，我会去试试的
